### PR TITLE
Another approach to multiple media servers (media_servers parameter)

### PR DESCRIPTION
**Pull request by dannygoulder**
Like #23 and #18, this allows you to configure multiple media servers by adding them as an array.

You could also combine a single media server with an array if desired.

This seems to be the most compatible approach.

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
Hej @dannygoulder, thanks for your work. I would prefer that $media_server is changed in a way that it accepts strings and arrays as input and uses an array in the template as output. So it should convert a string to an array with any2array() [1]. Think [2] could give you some inspiration.

[1] https://github.com/puppetlabs/puppetlabs-stdlib#any2array
[2] https://github.com/ghoneycutt/puppet-module-rsyslog/blob/89836714b8e3b15b51997fede71e0e76ba278e45/manifests/init.pp#L447-L457

In the meantime, I'll update the modules metadata to support Puppet 4.10 and keep support for Ruby 1.8.7.
This way you can create a commit that only takes care for the functionality itself.

**Comment by Phil-Friderici** [comment]
I have created another PR for adding multiple media servers functionality [1].
Please give it a test if it can fit your needs too and let me know.

[1] https://github.com/Ericsson/puppet-module-netbackup/pull/27

**Comment by Phil-Friderici** [comment]
Any chance for you to test my implementation ?

**Comment by dannygoulder** [comment]
Hi Phil,

Sorry haven't been able to test as I've just upgraded to 7.7.3.

Danny

**Comment by Phil-Friderici** [comment]
Thanks everyone, release v0.5.0 now includes support for multiple media servers.

**Pull request closed without merging**
