### PR TITLE
Fix multiple media servers feature

### PR DESCRIPTION
**Pull request by erobhal**
Changes the multiple media server feature in pull request https://github.com/Ericsson/puppet-module-netbackup/pull/18 to not break backward compability. Also updated documentation and spec test.

### CODE REVIEW

**Comment by erobhal** [comment]
Note: Travis CI test is failing on Ruby 187 with "Bundler could not find compatible versions for gem puppet-lint". That's not related to this commit.

**Comment by Phil-Friderici** [comment]
Agreed, Travis CI is failing because of missing updates to the setup.

**Comment by Phil-Friderici** [comment]
I have created another PR for adding multiple media servers functionality [1].
Please give it a test if it can fit your needs too and let me know.

[1] https://github.com/Ericsson/puppet-module-netbackup/pull/27

**Comment by Phil-Friderici** [comment]
Any chance for you to test my implementation ?

**Comment by NissesSenap** [comment]
Sorry for the very slow reply. I have tested and left a comment in the pull request.

**Comment by Phil-Friderici** [comment]
Thanks everyone, release v0.5.0 now includes support for multiple media servers.

**Pull request closed without merging**
